name: PHP Code Sniffer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v6

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: sockets, pdo_pgsql
        # Esto deshabilita Xdebug para que el proceso sea mucho más rápido
        coverage: none
    
    - name: Composer Install
      run: composer install --no-interaction --prefer-dist --optimize-autoloader
    
    - name: PHPCS
      run: composer run phpcs
