name: PHP Code Sniffer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v6

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: sockets, pdo_pgsql
        # Esto deshabilita Xdebug para que el proceso sea mucho más rápido
        coverage: none
    
    - name: Composer Install
      uses: php-actions/composer@v6
      with:
        php_extensions: sockets pdo_pgsql
    
    - name: PHPCS
      run: composer run phpcs
